// Exact instructor-provided entries mapped to fields used by this assignment page.
// Salary values are stored as numbers so salary sorting works numerically, not alphabetically.
const staffMembers = [
  { name: "Brielle Williamson", position: "Integration Specialist", salary: 372000 },
  { name: "Herrod Chandler", position: "Sales Assistant", salary: 137500 },
  { name: "Rhona Davidson", position: "Integration Specialist", salary: 327900 },
  { name: "Colleen Hurst", position: "Javascript Developer", salary: 205500 },
  { name: "Sonya Frost", position: "Software Engineer", salary: 103600 },
  { name: "Jena Gaines", position: "Office Manager", salary: 90560 },
  { name: "Quinn Flynn", position: "Support Lead", salary: 342000 },
  { name: "Tiger Nixon", position: "System Architect", salary: 320800 },
  { name: "Garrett Winters", position: "Accountant", salary: 170750 },
  { name: "Ashton Cox", position: "Junior Technical Author", salary: 86000 },
  { name: "Cedric Kelly", position: "Senior Javascript Developer", salary: 433060 },
  { name: "Airi Satou", position: "Accountant", salary: 162700 },
  { name: "Charde Marshall", position: "Regional Director", salary: 470600 },
  { name: "Haley Kennedy", position: "Senior Marketing Designer", salary: 313500 },
  { name: "Tatyana Fitzpatrick", position: "Regional Director", salary: 385750 },
  { name: "Michael Silva", position: "Marketing Designer", salary: 198500 },
  { name: "Paul Byrd", position: "Chief Financial Officer (CFO)", salary: 725000 },
  { name: "Gloria Little", position: "Systems Administrator", salary: 237500 },
  { name: "Bradley Greer", position: "Software Engineer", salary: 132000 },
  { name: "Dai Rios", position: "Personnel Lead", salary: 217500 },
  { name: "Jenette Caldwell", position: "Development Lead", salary: 345000 },
  { name: "Yuri Berry", position: "Chief Marketing Officer (CMO)", salary: 675000 },
  { name: "Caesar Vance", position: "Pre-Sales Support", salary: 106450 },
  { name: "Doris Wilder", position: "Sales Assistant", salary: 85600 },
  { name: "Angelica Ramos", position: "Chief Executive Officer (CEO)", salary: 1200000 },
  { name: "Gavin Joyce", position: "Developer", salary: 92575 },
  { name: "Jennifer Chang", position: "Regional Director", salary: 357650 },
  { name: "Brenden Wagner", position: "Software Engineer", salary: 206850 },
  { name: "Fiona Green", position: "Chief Operating Officer (COO)", salary: 850000 },
  { name: "Shou Itou", position: "Regional Marketing", salary: 163000 },
  { name: "Michelle House", position: "Integration Specialist", salary: 95400 },
  { name: "Suki Burks", position: "Developer", salary: 114500 },
  { name: "Prescott Bartlett", position: "Technical Author", salary: 145000 },
  { name: "Gavin Cortez", position: "Team Leader", salary: 235500 },
  { name: "Martena Mccray", position: "Post-Sales support", salary: 324050 },
  { name: "Unity Butler", position: "Marketing Designer", salary: 85675 }
];
